/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
/* Header for class com_pan_learn_ndk_more_TwoLibs */

#ifndef _Included_com_pan_learn_ndk_more_TwoLibs
#define _Included_com_pan_learn_ndk_more_TwoLibs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pan_learn_ndk_more_TwoLibs
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_pan_learn_ndk_more_TwoLibs_add
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jint JNICALL Java_com_pan_learn_ndk_more_TwoLibs_minus
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
