/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string.h>
/* Header for class com_pan_learn_ndk_simple_MainActivity */

#ifndef _Included_com_pan_learn_ndk_simple_MainActivity
#define _Included_com_pan_learn_ndk_simple_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pan_learn_ndk_simple_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pan_learn_ndk_simple_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
